### PR TITLE
Fixed overflow and alignment issues on homepage 

### PR DESCRIPTION
**Pull request by eeshaanSA**
## What's changed?
Fixed overflow issues, alignment issues and typos in : 

- Sponors Section 
- Dialog (Support HertzBeat)
- Friends Links

##Before the PR 
image
image
image

##After the PR is merged
image
image
image

Also Fixed some typos and spell errors here and there, as I found them. 

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by eeshaanSA** [comment]
Hey, @tomsun28. This is my first Pull request. Please give feedback. Will be more than happy to take it. Waiting for your reply.

**Comment by tomsun28** [comment]
> Hey, @tomsun28. This is my first Pull request. Please give feedback. Will be more than happy to take it. Waiting for your reply.

Hi, thanks for contributing. it look great!

**Review by tomsun28 — APPROVED** [review]

**Comment by tomsun28** [comment]
@all-contributors please add @eeshaanSA   for code

**Comment by eeshaanSA** [comment]
@tomsun28 please check #971 as well

**Pull request merged**
