### PR TITLE
support Influxdb monitoring

### PR DESCRIPTION
**Pull request by TJxiaobao**
## What's changed?

Complete influxdb monitoring and help document writing。

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi, it seems that we have created a new parsing method, but if the influxdb metrics interface returns the regular prometheus exporter format, we can directly use the prometheus parsing method, just like iotdb shenyu monitoring. 

```
    http:
      host: ^_^host^_^
      port: ^_^port^_^
      url: '/metrics'
      timeout: ^_^timeout^_^
      method: GET
      parseType: prometheus
```

**Comment by TJxiaobao** [comment]
Okay, I'll try to change it

**Comment by TJxiaobao** [comment]
Is that okay?
image

**Comment by TJxiaobao** [comment]
There is no data because the yml configuration is not configured properly, and this is the data after changing the configuration. Next I'll add a few more monitoring metrics and fix conflicts.
image

**Pull request closed without merging**
