### PR TITLE
feat: support hostname target

### LINKED ISSUE #1452: [Suggestion] Target Host support hostname entry
### Description

Monitor Target Host now only support ipv4, ipv6 and domain name entries. 
But in some situations, we only have the hostname of a target, which has no dot in the string.

Can we change the DOMAIN_SCHEMA pattern to support hostnames?

a working regex pattern is ^[-_a-zA-Z0-9\.]{0,99}$
i can create a pr if needed

### Task List

_No response_

### PR DESCRIPTION
**Pull request by ldysdu**
## support hostname target

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

close #1452

### CODE REVIEW

**Comment by tomsun28** [comment]
👍👍 hi, please help use fix the unit test error.

```
Error:  Failures: 
Error:    IpDomainUtilTest.validateIpDomain:43 expected: <false> but was: <true>
[INFO] 
Error:  Tests run: 37, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

```

**Comment by ldysdu** [comment]
updated the test case, improved the regex. 
wish you all have a happy new year!

**Comment by tomsun28** [comment]
@ldysdu Happy New Year!

**Comment by tomsun28** [comment]
hi, it seem something wrong in `Pattern.compile("^[-\w]+(\.[-\w]+)*$");` 


[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,34] illegal escape character
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,39] illegal escape character
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,43] illegal escape character
[INFO] 3 errors

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi, it seem something wrong in `Pattern.compile("^[-\w]+(\.[-\w]+)*$");` 


[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,34] illegal escape character
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,39] illegal escape character
Error:  /home/runner/work/hertzbeat/hertzbeat/common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java:[39,43] illegal escape character
[INFO] 3 errors

**Comment by ldysdu** [comment]
sorry for my poor java skill, and the poor network connection. 😂
a double slash should fix the illegal escape character issue hopefully.

**Comment by tomsun28** [comment]
@ldysdu No need to apologize, it’s a great job to take the first step contribute 👍

**Review by tomsun28 — APPROVED** [review]
LGTM！

**Comment by tomsun28** [comment]
@all-contributors please add @ldysdu for code

**Pull request merged**
