### PR TITLE
fix template files

### PR DESCRIPTION
**Pull request by l646505418**
## What's changed?

modify template yml files to replace # by /# for metric's calculates field

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi 这里不需要这样改 因为当 `#` 和之前的 `=` 紧挨一起的话，是不会被识别成注释标识符的
`cpu_load_average=#`$.os.cpu.load_average.1m` | $.os.load_average` 这样的表达式是正确的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hi, there is no need to change this way here, because when `#` is close to the previous `=`, it will not be recognized as a comment identifier
The expression `cpu_load_average=#`$.os.cpu.load_average.1m` | $.os.load_average` is correct

**Comment by l646505418** [comment]
> hi 这里不需要这样改 因为当 `#` 和之前的 `=` 紧挨一起的话，是不会被识别成注释标识符的 `cpu_load_average=#`$.os.cpu.load_average.1m` | $.os.load_average` 这样的表达式是正确的

好的好的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi There is no need to change this because when `#` is close to the previous `=`, it will not be recognized as a comment identifier `cpu_load_average=#`$.os.cpu.load_average.1m` | $ Expressions like .os.load_average` are correct

good good

**Comment by l646505418** [comment]
> hi 这里不需要这样改 因为当 `#` 和之前的 `=` 紧挨一起的话，是不会被识别成注释标识符的 `cpu_load_average=#`$.os.cpu.load_average.1m` | $.os.load_average` 这样的表达式是正确的

那之前那个对于#符号的enhangcement的那个pr有点多余了😂

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> hi There is no need to change this because when `#` is close to the previous `=`, it will not be recognized as a comment identifier `cpu_load_average=#`$.os.cpu.load_average.1m` | $ Expressions like .os.load_average` are correct

The previous PR for the enhancement of the # symbol is a bit redundant😂

**Comment by tomsun28** [comment]
> > hi 这里不需要这样改 因为当 `#` 和之前的 `=` 紧挨一起的话，是不会被识别成注释标识符的 `cpu_load_average=#`$.os.cpu.load_average.1m` | $.os.load_average` 这样的表达式是正确的
> 
> 那之前那个对于#符号的enhangcement的那个pr有点多余了😂

也不是多余的 支持两种方式嘛🐶

**Pull request closed without merging**
