### PR TITLE
support hertzbeat metrics collector cluster

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

support hertzbeat metrics collector cluster

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
image

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
image

**Comment by tomsun28** [comment]
image

**Comment by zqr10159** [comment]
太牛逼了，这码代码速度太快了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Awesome, this code is too fast

**Comment by tomsun28** [comment]
netty epoll server error when run in x86 docker container
```
# cat b561c74d79b910-2023-07-29-error.0.log
2023-07-29 23:42:03.529 [cluster netty server] ERROR org.dromara.hertzbeat.manager.scheduler.ManageServer Line:69  - incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
2023-07-29 23:42:03.534 [cluster netty server] ERROR org.dromara.hertzbeat.common.support.CommonThreadPool Line:48  - common executor has uncaughtException.
2023-07-29 23:42:03.537 [cluster netty server] ERROR org.dromara.hertzbeat.common.support.CommonThreadPool Line:49  - java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
java.lang.RuntimeException: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at org.dromara.hertzbeat.manager.scheduler.ManageServer.lambda$serverStartup$0(ManageServer.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:473)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:89)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:83)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:246)
	at org.dromara.hertzbeat.manager.scheduler.ManageServer.lambda$serverStartup$0(ManageServer.java:67)
	... 3 common frames omitted
```

**Comment by zqr10159** [comment]
采集器在哪里配置？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Where is the collector configured?

**Comment by tomsun28** [comment]
> 采集器在哪里配置？

需要先启动主服务器manager进程，然后启动 collector 模块进程，他们之间通信是在 collector 的 application.yml 文件配置 manager ip port那些

```
collector:
  dispatch:
    entrance:
      netty:
        enabled: true
        manager-ip: ${MANAGER_IP:localhost}
        manager-port: ${MANAGER_PORT:1158}
```

image

**Comment by zqr10159** [comment]
也就是说将来采集器可以单独部署？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
That is to say, the collector can be deployed separately in the future?

**Review by zqr10159 — APPROVED** [review]

**Comment by tomsun28** [comment]
> 也就是说将来采集器可以单独部署？

是的 可以多个采集器集群横行扩展

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> In other words, the collector can be deployed separately in the future?

Yes, multiple collector clusters can be expanded horizontally

**Comment by tomsun28** [comment]
稍等 刚发现点问题修复下

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Wait a minute, I just found some bugs and fixed them

**Comment by tomsun28** [comment]
arch

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
arch

**Review by Ceilzcx — APPROVED** [review]

**Pull request merged**
