### PR TITLE
Feature: http_sd monitor

### PR DESCRIPTION
**Pull request by Calvin979**
## What's changed?
#1526 
支持Http sd监控。
因使用Spring Cloud提供的统一接口DiscoveryClient对代码改动较大，目前采用了各个注册中心原生的SDK进行监控。
> 目前只添加了最常见的两种注册中心：Consul和Nacos，如果后期需要接入更多注册中心，我开放了一个接口org.dromara.hertzbeat.collector.collect.httpsd.discovery.DiscoveryClient，直接实现该接口即可。
代码位置：
image

本地调试结果：
httpsd
consul

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
NB Plus!

**Review by tomsun28 — APPROVED** [review]
LGTM!👍👍

**Comment by tomsun28** [comment]
@all-contributors please add @Calvin979 for doc, code, design

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@all-contributors please add @Calvin979 for doc, code, design

**Comment by Calvin979** [comment]
> Great! This feature we support monitoring nacos consul throught http_sd protocol. How about this other feature, we auto discovery monitoring instance throught http_sd, like prometheus discovery. Like this:
> 
> 1. http request `http_sd` api to get service instance ip, port and more.
> 2. auto create monitor to monitoring service instance throght prometheus protocol
> 
> This is more complicated and needs to be designed carefully.

I'd like to try! Should we create another issue to trace it?

**Comment by tomsun28** [comment]
> I'd like to try! Should we create another issue to trace it? 

welcome, yes we can create a issue to trace and discuss it.

**Comment by Calvin979** [comment]
> > I'd like to try! Should we create another issue to trace it?
> 
> welcome, yes we can create a issue to trace and discuss it.

I've created an issue.
#1625

**Pull request merged**
