### PR TITLE
[fix] Restructured & fixed navbar overflow

### PR DESCRIPTION
**Pull request by Neilblaze**
### What's changed?
Reorganized home navbar & fixed overflow issue. A few typos were discovered during the process which were also fixed.
/cc: @tomsun28  >>  [Reference](https://matrix.to/#/!EuqIIXwegYbgoaMopS:gitter.im/$GX1_Qx_VlP-WQogoTNuUQHK_UcQ76BhhSt-dzEObNqY?via=gitter.im)

### Demo / Screenshot
Recording20230513

### Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.

### CODE REVIEW

**Review by tomsun28 — APPROVED** [review]
Great! 😄 LGTM, thanks very much.

**Comment by tomsun28** [comment]
@all-contributors please add @Neilblaze for doc, code

**Comment by Neilblaze** [comment]
@tomsun28 would you mind taking a look at gitter, please? Thanks!

**Comment by tomsun28** [comment]
ok

**Pull request merged**
