### PR TITLE
[讨论] 是否需要代码中更多替换使用java8+的高阶函数，如下代码替换是否合适

### PR DESCRIPTION
**Pull request by LINGLUOJUN**
## What's changed?

[讨论] 是否需要代码中更多替换使用java8+的高阶函数与方法
 优点:
- 减少诸如if else+for 带来的嵌套问题
- 精简代码

讨论点：如下代码替换是否合适

3351694656711_ pic

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by gcdd1993** [comment]
支持，右侧代码逻辑看起来更加清晰，重点倒不是用不用Stream流

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Yes, the code logic on the right looks clearer. The point is not whether to use Stream or not.

**Comment by Ceilzcx** [comment]
每个人代码习惯不太一样，个人感觉这种流式的写法不是太必要，确实有一点影响代码可读性和debug。
如果觉得if嵌套多，其实改成 if(xxx == null) return; 的写法也可以减少if嵌套，有些for循环改成嵌套可以

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Everyone's coding habits are different. I personally feel that this flow-style writing method is not necessary. It does affect code readability and debugging.
If you feel that there are too many if nests, you can actually change it to if(xxx == null) return; which can also reduce the if nesting. Some for loops can be changed to nested ones.

**Comment by hudongdong129** [comment]
从代码量和编写来说，使用stream流会更优雅点，如果steam流程太多，对debug和排查问题感觉不是太友好

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
In terms of code volume and writing, using streams will be more elegant. If there are too many steam processes, it will not be very friendly for debugging and troubleshooting.

**Comment by hudongdong129** [comment]
stream流使用的都是不可变量，如果需要在集合中，传入外部变量进行修改，只能使用for-each这种

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Streams use immutable variables. If you need to pass in external variables for modification in a collection, you can only use for-each.

**Comment by Carpe-Wang** [comment]
我觉得流式编程更好吧，也是一个技术趋势，并且更容易看懂啊。我赞成流

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I think flow programming is better, it is also a technical trend, and it is easier to understand. I agree with the flow

**Comment by VampireAchao** [comment]
Less nested?Yes! Abuse lambda?No

**Comment by tomsun28** [comment]
个人观点，左边一个非java的就能看懂 右边就难了 debug也难。流可以用在真正的集合处理的时候，仓库里面很多代码处理集合流都会用，optional一般用在返回值，让调用强制处理空情况，仓库里面一般在查询数据库记录会用到。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
From my personal point of view, a non-java person on the left can understand it, but the right one is more difficult, and debugging is also difficult. Streams can be used in real collection processing. Many codes in the warehouse use collection streams. Optional is generally used in return values ​​to force calls to handle empty situations. In warehouses, it is generally used when querying database records.

**Comment by wang1027-wqh** [comment]
其实有很多办法可以减少嵌套层数嘛，只是说看起来高不高级。牛不牛逼，一些简单的判断确实使用流更加美观简洁，但是如果各个逻辑下有比较复杂的业务，我觉得大多还是使用设计模式来拆分吧，作为一个写CRUD写的很多的人来说，有些if确实不省略更容易读懂更容易维护。右边这种可以优化一下注释。这样也能补足一点短板

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
In fact, there are many ways to reduce the number of nesting levels, it just looks high-level or not. Awesome or not, some simple judgments are indeed more beautiful and concise using flows, but if there are more complex businesses under each logic, I think most of them should be split using design patterns. As a person who writes a lot of CRUD , some ifs are indeed easier to read and maintain if they are not omitted. The comment on the right can be optimized. This can also make up for some shortcomings

**Comment by zqr10159** [comment]
简单的逻辑不是很有必要改成流，反而影响可读性。在集合处理方面可以多多使用。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is not necessary to change simple logic to a stream, but it will affect readability. It can be used a lot in collection processing.

**Pull request closed without merging**
