### PR TITLE
[monitor] support ssl certificate expired monitor

### PR DESCRIPTION
**Pull request by tomsun28**

### CODE REVIEW

**Comment by tomsun28** [comment]
link https://github.com/dromara/hertzbeat/issues/255

**Comment by gcdd1993** [comment]
SSL证书支持到期X天通知提醒吗？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Does the SSL certificate support X days notification reminder?

**Comment by tomsun28** [comment]
支持的 可以参考这个 https://hertzbeat.com/docs/start/ssl-cert-practice 配置阈值

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Supported, you can refer to this https://hertzbeat.com/docs/start/ssl-cert-practice to configure the threshold

**Pull request merged**
