### PR TITLE
support config common aes secret

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

support config common aes secret

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
todo, consider not init cipher in AesUtil every time and test performance

**Comment by ZY945** [comment]
> todo, consider not init cipher in AesUtil every time and test performance

Does this mean using singleton (not every initialization)?

**Comment by tomsun28** [comment]
> Does this mean using singleton (not every initialization)?

image

here we init `cipher` every time, want to try just initialize the `cipher` once and then support its use by multiple threads safely.

**Comment by ZY945** [comment]
> > Does this mean using singleton (not every initialization)?
> 
> image
> here we init `cipher` every time, want to try just initialize the `cipher` once and then support its use by multiple threads safely.

image
I found a place to set the SecretKey, and we can try initializing Cipher by putting it into the setDefultSecretKey method.

**Comment by ZY945** [comment]
> > I found a place to set the SecretKey, and we can try initializing Cipher by putting it into the setDefultSecretKey method.
> 
> yes, and we should consider the situation that not `setDefultSecretKey` when startup.

image
image
image
Is this method okay? A single instance of double check lock

**Review by ZY945 — APPROVED** [review]
LGTM

**Pull request merged**
