### PR TITLE
Update app-windows.yml

### PR DESCRIPTION
**Pull request by lfandrh**
Fix the issue of Windows memory usage exceeding 100%

### CODE REVIEW

**Comment by lfandrh** [comment]
提交的这部分代码不能彻底解决Winodws物理内存使用率超100%或不显示的问题，因为物理内存的已使用部分是通过存储信息来获取的，而存储信息又包括分区信息，所以iod的最后一位实际上跟电脑分区的数量是有关联的，比如电脑有4个分区，oid的最后一位是6才能获取到正确的信息，如有5个分区，oid的最后一位是7才能获取到正确信息，但配置文件的内容是固定的，所以需要修改后端snmp代码才能彻底解决这个问题。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This part of code submitted cannot completely solve the problem that Winodws physical memory usage exceeds 100% or does not display, because the used part of physical memory is obtained through storage information, and storage information includes partition information, so the last iod The bit is actually related to the number of computer partitions. For example, if the computer has 4 partitions, the last digit of the oid is 6 to get the correct information. If there are 5 partitions, the last digit of the oid is 7 to get the correct information. The information is correct, but the content of the configuration file is fixed, so the backend snmp code needs to be modified to completely solve this problem.

**Comment by tomsun28** [comment]
hi 是的 我们也发现了这个问题 最后一位类似于分区索引

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi yes we found this problem too the last bit is similar to the partition index

**Comment by lfandrh** [comment]
> hi 是的 我们也发现了这个问题 最后一位类似于分区索引

嗯嗯，我目前是修改了src/main/java/org/dromara/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java文件，思路是：捕获申请hrMemorySize信息的请求，然后直接把存储信息的最后一条信息(实际就是内存信息)解析处理之后返回，这样来解除内存信息与分区个数的关联性。
然后还需要修改一下src/main/resources/define/app-windows.yml与内存有关的那部分代码里面的calculates，代码放下面，可以参考一下。

SnmpCollectImpl.java
```
    @Override
    public void collect(CollectRep.MetricsData.Builder builder, long appId, String app, Metrics metrics) {
        long startTime = System.currentTimeMillis();
        // 校验参数
        try {
            validateParams(metrics);
        } catch (Exception e) {
            builder.setCode(CollectRep.Code.FAIL);
            builder.setMsg(e.getMessage());
            return;
        }
        SnmpProtocol snmpProtocol = metrics.getSnmp();
        int timeout = CollectUtil.getTimeout(snmpProtocol.getTimeout());
        int snmpVersion = getSnmpVersion(snmpProtocol.getVersion());
        try {
            SnmpBuilder snmpBuilder = new SnmpBuilder();
            Snmp snmpService = getSnmpService(snmpVersion);
            Target<?> target;
            Address targetAddress = GenericAddress.parse(DEFAULT_PROTOCOL + ":" + snmpProtocol.getHost()
                    + "/" + snmpProtocol.getPort());
            TargetBuilder<?> targetBuilder = snmpBuilder.target(targetAddress);
            if (snmpVersion == SnmpConstants.version3) {
                target = targetBuilder
                        .user(snmpProtocol.getUsername())
                        .auth(TargetBuilder.AuthProtocol.hmac192sha256).authPassphrase(snmpProtocol.getAuthPassphrase())
                        .priv(TargetBuilder.PrivProtocol.aes128).privPassphrase(snmpProtocol.getPrivPassphrase())
                        .done()
                        .timeout(timeout).retries(1)
                        .build();
            } else if (snmpVersion == SnmpConstants.version1) {
                target = targetBuilder
                        .v1()
                        .community(new OctetString(snmpProtocol.getCommunity()))
                        .timeout(timeout).retries(1)
                        .build();
                target.setSecurityModel(SecurityModel.SECURITY_MODEL_SNMPv1);
            } else {
                target = targetBuilder
                        .v2c()
                        .community(new OctetString(snmpProtocol.getCommunity()))
                        .timeout(timeout).retries(1)
                        .build();
                target.setSecurityModel(SecurityModel.SECURITY_MODEL_SNMPv2c);
            }
            String operation = snmpProtocol.getOperation();
            operation = StringUtils.hasText(operation) ? operation : OPERATION_GET;

            //此if是为了解决内存信息与分区个数相依赖的问题
            //思路是：先捕获到获取内存信息的请求，其Oids中必定包含"hrStorageDescr"关键字
            //      然后获取存储信息（存储信息中包含了内存信息），然后获取到内存信息，然后将内存信息返回
            //      但获取到的数据的单位跟原请求的数据单位是不一致的，所以要在app-windows.yml中将单位进行转换
            Map<String, String> myOidsMap1 = snmpProtocol.getOids();
            if (myOidsMap1.containsKey("hrMemorySize")){
                //添加获取存储信息的oid
                Map<String, String> oidMap = snmpProtocol.getOids();
                oidMap.put("hrStorageDescr","1.3.6.1.2.1.25.2.3.1.3");
                oidMap.put("hrStorageSize","1.3.6.1.2.1.25.2.3.1.5");
                oidMap.put("hrStorageUsed","1.3.6.1.2.1.25.2.3.1.6");
                oidMap.put("hrStorageAllocationUnits","1.3.6.1.2.1.25.2.3.1.4");
                //这段代码原封不动，使用的还是walk请求的代码
                TableUtils tableUtils = new TableUtils(snmpService, new DefaultPDUFactory(PDU.GETBULK));
                OID[] oids = oidMap.values().stream().map(OID::new).toArray(OID[]::new);
                List<TableEvent> tableEvents = tableUtils.getTable(target, oids, null, null);
                ListIterator<TableEvent> iterator = tableEvents.listIterator();
                long responseTime = System.currentTimeMillis() - startTime;

                //因为要获取的物理内存数据是最后一个数据，所以要使用迭代器来判断是否是最后一个元素
                while (iterator.hasNext()){
                    TableEvent tableEvent = iterator.next();
                    if (tableEvent == null || tableEvent.isError()) {
                        continue;
                    }
                    VariableBinding[] varBindings = tableEvent.getColumns();
                    Map<String, String> oidsValueMap = new HashMap<>(varBindings.length);
                    for (VariableBinding binding : varBindings) {
                        if (binding == null) {
                            continue;
                        }
                        Variable variable = binding.getVariable();
                        if (variable instanceof TimeTicks) {
                            String value = ((TimeTicks) variable).toString(FORMAT_PATTERN);
                            oidsValueMap.put(binding.getOid().trim().toDottedString(), value);
                        } else {
                            oidsValueMap.put(binding.getOid().trim().toDottedString(), bingdingHexValueToString(binding));
                        }
                    }
                    // when too many empty value field, ignore
                    if (oidsValueMap.size() < metrics.getAliasFields().size() / 2) {
                        continue;
                    }
                    //获取到数据后，用yml文件中的oid来获取对应的值，所以要对值进行替换，否则获取不到1.3.6.1.2.1.25.2.2.0对应的物理内存总大小信息
                    CollectRep.ValueRow.Builder valueRowBuilder = CollectRep.ValueRow.newBuilder();
                    String s = oidsValueMap.get("1.3.6.1.2.1.25.2.3.1.5");
                    System.out.println(s);
                    oidsValueMap.put("1.3.6.1.2.1.25.2.2.0",s);
                    //如果没有获取到值，就不能向builder中添加数据，flag就是用来避免其无数据时向builder中添加数据
                    int flag = 0;
                    for (String alias : metrics.getAliasFields()) {
                        if (!CollectorConstants.RESPONSE_TIME.equalsIgnoreCase(alias)) {
                            String oid = oidMap.get(alias);
                            String value = oidsValueMap.get(oid);
                            if (value != null) {
                                if (!iterator.hasNext()){
                                    valueRowBuilder.addColumns(value);
                                }else {
                                    flag=1;
                                }

                            } else {
                                if (!iterator.hasNext()){
                                    valueRowBuilder.addColumns(CommonConstants.NULL_VALUE);
                                }else {
                                    flag=1;
                                }

                            }
                        }
                    }

                    if (flag==1){
                        continue;
                    }

//                    System.out.println(valueRowBuilder.getColumns(0));
//                    System.out.println(valueRowBuilder.getColumns(1));
//                    System.out.println(valueRowBuilder.getColumns(2));

                    builder.addValues(valueRowBuilder.build());
                }
            }else{
                //如果没有捕获到获取内存信息的请求，就跟原来的处理方法一样
                if (OPERATION_GET.equalsIgnoreCase(operation)) {
                    PDU pdu = targetBuilder.pdu().type(PDU.GET).oids(snmpProtocol.getOids().values().toArray(new String[0])).build();
                    SnmpCompletableFuture snmpRequestFuture = SnmpCompletableFuture.send(snmpService, target, pdu);
                    List<VariableBinding> vbs = snmpRequestFuture.get().getAll();
                    long responseTime = System.currentTimeMillis() - startTime;
                    Map<String, String> oidsMap = snmpProtocol.getOids();
                    Map<String, String> oidsValueMap = new HashMap<>(oidsMap.size());
                    for (VariableBinding binding : vbs) {
                        if (binding == null) {
                            continue;
                        }
                        Variable variable = binding.getVariable();
                        if (variable instanceof TimeTicks) {
                            String value = ((TimeTicks) variable).toString(FORMAT_PATTERN);
                            oidsValueMap.put(binding.getOid().toDottedString(), value);
                        } else {
                            oidsValueMap.put(binding.getOid().toDottedString(), binding.toValueString());
                        }
                    }
                    CollectRep.ValueRow.Builder valueRowBuilder = CollectRep.ValueRow.newBuilder();
                    for (String alias : metrics.getAliasFields()) {
                        if (CollectorConstants.RESPONSE_TIME.equalsIgnoreCase(alias)) {
                            valueRowBuilder.addColumns(Long.toString(responseTime));
                        } else {
                            String oid = oidsMap.get(alias);
                            String value = oidsValueMap.get(oid);
                            if (value != null) {
                                valueRowBuilder.addColumns(value);
                            } else {
                                valueRowBuilder.addColumns(CommonConstants.NULL_VALUE);
                            }
                        }
                    }
                    builder.addValues(valueRowBuilder.build());
                } else if (OPERATION_WALK.equalsIgnoreCase(operation)) {
                    Map<String, String> oidMap = snmpProtocol.getOids();

                    Assert.notEmpty(oidMap, "snmp oids is required when operation is walk.");
                    TableUtils tableUtils = new TableUtils(snmpService, new DefaultPDUFactory(PDU.GETBULK));
                    OID[] oids = oidMap.values().stream().map(OID::new).toArray(OID[]::new);
                    List<TableEvent> tableEvents = tableUtils.getTable(target, oids, null, null);
                    Assert.notNull(tableEvents, "snmp walk response empty content.");
                    long responseTime = System.currentTimeMillis() - startTime;
                    for (TableEvent tableEvent : tableEvents) {
                        if (tableEvent == null || tableEvent.isError()) {
                            continue;
                        }
                        VariableBinding[] varBindings = tableEvent.getColumns();
                        Map<String, String> oidsValueMap = new HashMap<>(varBindings.length);
                        for (VariableBinding binding : varBindings) {
                            if (binding == null) {
                                continue;
                            }
                            Variable variable = binding.getVariable();
                            if (variable instanceof TimeTicks) {
                                String value = ((TimeTicks) variable).toString(FORMAT_PATTERN);
                                oidsValueMap.put(binding.getOid().trim().toDottedString(), value);
                            } else {
                                oidsValueMap.put(binding.getOid().trim().toDottedString(), bingdingHexValueToString(binding));
                            }
                        }
                        // when too many empty value field, ignore
                        if (oidsValueMap.size() < metrics.getAliasFields().size() / 2) {
                            continue;
                        }
                        CollectRep.ValueRow.Builder valueRowBuilder = CollectRep.ValueRow.newBuilder();
                        for (String alias : metrics.getAliasFields()) {
                            if (CollectorConstants.RESPONSE_TIME.equalsIgnoreCase(alias)) {
                                valueRowBuilder.addColumns(Long.toString(responseTime));
                            } else {
                                String oid = oidMap.get(alias);
                                String value = oidsValueMap.get(oid);
                                if (value != null) {
                                    valueRowBuilder.addColumns(value);
                                } else {
                                    valueRowBuilder.addColumns(CommonConstants.NULL_VALUE);
                                }
                            }
                        }
                        builder.addValues(valueRowBuilder.build());
                    }
                }
            }

        } catch (ExecutionException | InterruptedException ex) {
            String errorMsg = CommonUtil.getMessageFromThrowable(ex);
            log.warn("[snmp collect] error: {}", errorMsg);
            builder.setCode(CollectRep.Code.UN_CONNECTABLE);
            builder.setMsg(errorMsg);
        } catch (Exception e) {
            String errorMsg = CommonUtil.getMessageFromThrowable(e);
            log.warn("[snmp collect] error: {}", errorMsg, e);
            builder.setCode(CollectRep.Code.FAIL);
            builder.setMsg(errorMsg);
        }
    }
```
```
  - name: memory
    priority: 1
    fields:
      - field: total
        type: 0
        unit: GB
      - field: used
        type: 0
        unit: GB
      - field: usage
        type: 0
        unit: '%'
    # (optional)metrics field alias name, it is used as an alias field to map and convert the collected data and metrics field
    # (可选)监控指标别名, 做为中间字段与采集数据字段和指标字段映射转换
    aliasFields:
      - hrMemorySize
      - hrStorageUsed
      - hrStorageAllocationUnits
    # mapping and conversion expressions, use these and aliasField above to calculate metrics value
    # (可选)指标映射转换计算表达式,与上面的别名一起作用,计算出最终需要的指标值
    # eg: cores=core1+core2, usage=usage, waitTime=allTime-runningTime
    calculates:
      - total=hrMemorySize * hrStorageAllocationUnits / 1024
      - used=hrStorageUsed * hrStorageAllocationUnits
      - usage= hrStorageUsed * hrStorageAllocationUnits / (hrMemorySize * hrStorageAllocationUnits) * 100
    units:
      - total=KB->GB
      - used=B->GB
    protocol: snmp
    snmp:
      host: ^_^host^_^
      port: ^_^port^_^
      timeout: ^_^timeout^_^
      community: ^_^community^_^
      version: ^_^version^_^
      operation: get
      oids:
        hrMemorySize: 1.3.6.1.2.1.25.2.2.0
        hrStorageUsed: 1.3.6.1.2.1.25.2.3.1.6.6
        hrStorageAllocationUnits: 1.3.6.1.2.1.25.2.3.1.4.6
```

**Pull request closed without merging**
