### PR TITLE
initial mongodb support

### PR DESCRIPTION
**Pull request by liudonghua123**

### CODE REVIEW

**Review by tomsun28 — APPROVED** [review]
👍👍👍 Great! Thanks, LGTM.

**Comment by tomsun28** [comment]
@all-contributors please add @liudonghua123  for code, ideas

@liudonghua123  thanks for contributing👍, please fix the 3 PMD violations error in java ci.  https://github.com/dromara/hertzbeat/actions/runs/3815021810/jobs/6489928797

**Comment by liudonghua123** [comment]
@tomsun28 Thanks for the quick code review, I have fixed the PMD violations error in [github ci](https://github.com/dromara/hertzbeat/actions/runs/3815021810/jobs/6489928797) now.

**Comment by tomsun28** [comment]
@liudonghua123 thanks! Happy New Year

**Pull request merged**
