### PR TITLE
update to Springboot3

### PR DESCRIPTION
**Pull request by zqr10159**
## What's changed?

update to Springboot3

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
👍👍👍

**Comment by gcdd1993** [comment]
@zqr10159 SpringBoot3是否依赖Jdk17？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@zqr10159 Does SpringBoot3 depend on Jdk17?

**Comment by zqr10159** [comment]
是的，必须jdk17以上发自我的 iPhone在 2023年9月28日，18:11，进击的阿晨 ***@***.***> 写道：﻿
@zqr10159 SpringBoot3是否依赖Jdk17？

**Comment by zqr10159** [comment]
> @zqr10159 SpringBoot3是否依赖Jdk17？

是的，必须17以上

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> @zqr10159 Does SpringBoot3 depend on Jdk17?

Yes, must be 17 or above

**Pull request merged**
