### PR TITLE
[ospp] add push style collector doc

### PR DESCRIPTION
**Pull request by vinci-897**
## What's changed?

由于代码pr预计将在10.7之前合并，为了防止之后至10.30之间无法再向ospp官网提交新的文档pull request链接，因此先行创建这一pr来便于之后提交相关文档

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by vinci-897** [comment]
done

**Comment by tomsun28** [comment]
👍👍 hi please add i18n cn doc here https://github.com/dromara/hertzbeat/tree/master/home/i18n/zh-cn/docusaurus-plugin-content-docs/current/advanced 

we can config the web doc menus by sidebars.json  https://github.com/dromara/hertzbeat/blob/master/home/sidebars.json#L43

**Comment by vinci-897** [comment]
加上了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
added

**Review by Ceilzcx — APPROVED** [review]
LGTM

**Pull request merged**
