### PR TITLE
support query monitors by tags filter

### PR DESCRIPTION
**Pull request by l646505418**
## What's changed?

add monitorGroup in `Monitor` and modify query API to support group monitor

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by l646505418** [comment]
Hi @tomsun28  ,I have modified the backend codes, maybe need some guys to modify frontend code

**Comment by l646505418** [comment]
> 

我觉得不错，hhh

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
>

I feel good, hhh

**Comment by l646505418** [comment]
> 用标签来进行分组怎么样，我们有标签功能，用户给监控打上特定的一类标签，然后用标签来查询过滤一组监控

Hi，那后端接受的param是list<Tag>呢还是一个json字符串？

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> How about using tags to group? We have a tag function. Users can tag a specific type of monitoring, and then use tags to query and filter a group of monitoring

Hi, is the param accepted by the backend a list<Tag> or a json string?

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > How about using tags to group? We have a tag function. Users can tag a specific type of monitoring, and then use tags to query and filter a group of monitoring
>
> Hi, is the param accepted by the backend a list or a json string?

Label array, that is, our monitoring query supports a wave of filtering queries based on labels

**Comment by l646505418** [comment]
Hi @tomsun28 ，I have modified the code to support group by tag and query by tag list, you can review

**Comment by tomsun28** [comment]
> Hi @tomsun28 ，I have modified the code to support group by tag and query by tag list, you can review
👍 ok

**Review by tomsun28 — APPROVED** [review]
LGTM👍👍

**Pull request merged**
