### PR TITLE
[hertzbeat] release hertzbeat version v1.3.1

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

release hertzbeat version v1.3.1

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by zqr10159** [comment]
要发新版本了吗

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Are you going to release a new version?

**Comment by tomsun28** [comment]
> 要发新版本了吗

是的准备今天发😊

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Are you going to release a new version?

Yes, ready to post today 😊

**Pull request merged**
