### PR TITLE
bugfix monitoring job not change when update monitoring define config

### PR DESCRIPTION
**Pull request by sunqinbo**
解决 ：模板修改后，同类型模板的所有监控实例 ，在监控状态中，需要重新下发任务

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Review by tomsun28 — APPROVED** [review]
LGTM!

**Comment by tomsun28** [comment]
@hudongdong129 dongdong 有空帮忙 reivew 下这个 redis 的改动

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@hudongdong129 dongdong is free to help reivew this redis change

**Review by hudongdong129 — COMMENTED** [review]
redis info itself contains these instructions, if you don't need to monitor whether it can be deleted in the custom yml

**Comment by sunqinbo** [comment]
测试使用redis版本 ：5.0.4，不包含process_supervised，server_time_usec，io_threads_active

删除原因是org.dromara.hertzbeat.collector.dispatch.MetricsCollect#calculateFields() 224报错；
当redis 返回结果集小于映射字段数量，就会出现索引越界问题；
使用自定义监控是可以解决这个问题，需要优化错误提示，告知使用者，指标组中的哪个指标是无效。


image
image

**Comment by hudongdong129** [comment]
@sunqinbo 看redis官方文档 版本大于2.4的都有这些值
image 应该是有些值在没有触发的时候是没有值的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@sunqinbo Look at the official redis documentation, versions greater than 2.4 have these values
image It should be that some values ​​have no value when there is no trigger

**Comment by hudongdong129** [comment]
@sunqinbo 如果返回的值小于配置的值 就报数组越界的话 其他监控的数据可能也有这样的问题

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@sunqinbo If the returned value is less than the configured value, it will report that the array is out of bounds. Other monitored data may also have such problems

**Comment by sunqinbo** [comment]
@reference https://github.com/dromara/hertzbeat/pull/913
The fix array is out of bounds.
If the number of returned metrics is less than the sum of the metrics configured by YML, fill in the default value by the indicator type configured by YML: 0 number 1 String.

**Comment by sunqinbo** [comment]
指标为number类型时，表示状态的，默认赋值0的问题
```java
    private Map<String, String> parseInfo(String info, Metrics metrics) {
        // yml配置的指标总和
        int fieldTotalSize = metrics.getFields().size();
        String[] lines = info.split(SignConstants.LINE_FEED);
        Map<String, String> result = new HashMap<>(MapCapUtil.calInitMap(fieldTotalSize));

        Arrays.stream(lines)
                .filter(it -> StringUtils.hasText(it) && !it.startsWith(SignConstants.WELL_NO) && it.contains(SignConstants.DOUBLE_MARK))
                .map(this::removeCr)
                .map(r -> r.split(SignConstants.DOUBLE_MARK))
                .forEach(it -> {
                    result.put(it[0], it[1]);
                });
        // https://github.com/dromara/hertzbeat/pull/913
        // fix 数组越界
        // 如果返回的指标数量小于yml配置的指标总和，按yml配置指标类型填充默认值： 0 number 1 String
        if (result.size() < fieldTotalSize) {
            for (Metrics.Field field : metrics.getFields()) {
                if (!result.containsKey(field.getField())) {
                    if (field.getType() == 0) {
                        result.put(field.getField(), Double.valueOf(0).toString());
                    } else {
                        result.put(field.getField(), CommonConstants.NULL_VALUE);
                    }
                }
            }
        }
        return result;
    }
```

问题代码如下
```java
if (field.getType() == 0) {
       result.put(field.getField(), Double.valueOf(0).toString());
 }
```
`field.getType() == 0`是通过配置文件获取字段类型，number或String；如果info命令执行后，返回的查询结果总和，小于yml配置指标总和时，当存在number类型，如果赋值0，可能会有争议；

比如指标 cluster_enabled：表示是否启用 Redis 集群；0未启用 1启用；

在redis 2.8版本中查询返回的数据如下，但是2.8是否支持集群功能，查阅了官方文档没有具体说明。
image

在redis 5.0.4版本中查询返回的数据如下：
image

推荐：
image

```java
    private Map<String, String> parseInfo(String info, Metrics metrics) {
        // yml配置的指标总和
        int fieldTotalSize = metrics.getFields().size();
        String[] lines = info.split(SignConstants.LINE_FEED);
        Map<String, String> result = new HashMap<>(MapCapUtil.calInitMap(fieldTotalSize));

        Arrays.stream(lines)
                .filter(it -> StringUtils.hasText(it) && !it.startsWith(SignConstants.WELL_NO) && it.contains(SignConstants.DOUBLE_MARK))
                .map(this::removeCr)
                .map(r -> r.split(SignConstants.DOUBLE_MARK))
                .forEach(it -> {
                    result.put(it[0], it[1]);
                });
        // https://github.com/dromara/hertzbeat/pull/913
        // fix 数组越界
        // 如果返回的指标数量小于yml配置的指标总和，按yml配置指标类型填充默认值： 0 number 1 String
        if (result.size() < fieldTotalSize) {
            for (Metrics.Field field : metrics.getFields()) {
                if (!result.containsKey(field.getField())) {
                    result.put(field.getField(), CommonConstants.NULL_VALUE);
                }
            }
        }
        return result;
    }
```

**Pull request closed without merging**
