### PR TITLE
Add Grafana Dashboard

### PR DESCRIPTION
**Pull request by zqr10159**
## What's changed?

Add Grafana Dashboard

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by zqr10159** [comment]
@tomsun28 Please help resolve conflicts and review these pulls, and package with grafana.
Grafana allows anonymous and embedding:
https://juejin.cn/post/7098632520513617957

**Comment by tomsun28** [comment]
ok!👍

**Comment by tomsun28** [comment]
hi, are the latest code is branch `zqr10159:grafana` ?

**Comment by zqr10159** [comment]
> hi, are the latest code is branch `zqr10159:grafana` ?

yes

**Review by tomsun28 — APPROVED** [review]
LGTM!

**Pull request merged**
