### PR TITLE
[test] add junit WarehouseWorkerPoolTest

### PR DESCRIPTION
**Pull request by TherChenYang**

### CODE REVIEW

**Comment by tomsun28** [comment]
Hi thanks, please use `assert` to instead of `System.out.println`

**Comment by TherChenYang** [comment]
> Hi thanks, please use `assert` to instead of `System.out.println`

Okay, I'll make the changes right away.

**Comment by TherChenYang** [comment]
> Hi thanks, please use `assert` to instead of `System.out.println`

I have made changes to the code, please check

**Review by tomsun28 — APPROVED** [review]
Thanks! LGTM!👍👍

**Comment by TherChenYang** [comment]
I'm sorry for ignoring a small detail. Please complete the ci detection workflow

**Comment by tomsun28** [comment]
@all-contributors please add @TherChenYang for code, test.   
Thanks for pr. @TherChenYang can you help us to update this test case https://github.com/dromara/hertzbeat/pull/565 https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/AlerterWorkerPoolTest.java

**Review by rellyrell7898 — APPROVED** [review]

**Review by rellyrell7898 — APPROVED** [review]

**Pull request merged**
