### PR TITLE
Fixed Carousel Overflow on homepage and made it responsive

### PR DESCRIPTION
**Pull request by eeshaanSA**
## What's changed?
The Logo and Dromara Friends Carousel was breaking for mobile and tablet devices. check https://hertzbeat.com/
I made the nesccessary changes to make the carousel responsive. 

## Before the PR : 
image
image

## Carousels after PR gets merged : 
[Screencast from 21-05-23 02:08:48 PM IST.webm](https://github.com/dromara/hertzbeat/assets/100678386/f1814fbf-f190-4d32-a157-ad0d54838bdb)

## Checklist
- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by eeshaanSA** [comment]
@tomsun28  please have a look :hugs:

**Review by tomsun28 — APPROVED** [review]
LGTM!👍

**Comment by eeshaanSA** [comment]
@tomsun28 needed to have to chat with you. When is the right time for you? I wont take long? PLease let me know.

**Review by Neilblaze — APPROVED** [review]

**Comment by tomsun28** [comment]
> @tomsun28 needed to have to chat with you. When is the right time for you? I wont take long. Please let me know.

hi i have chat in gitter with you.

**Pull request merged**
