### PR TITLE
Staus Page Component

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

- status page sql design

```sql
-- ----------------------------
-- Table structure for hzb_status_page_org
-- ----------------------------
DROP TABLE IF EXISTS  hzb_status_page_org ;
CREATE TABLE  hzb_status_page_org
(
    id           bigint           not null auto_increment comment 'ID',
    name         varchar(255)     not null comment 'org name',
    desc         varchar(255)     comment 'org description',
    home         varchar(255)     not null comment 'org home link',
    logo         longtext         comment 'org logo pic, only support svg format',
    creator      varchar(100)     comment 'creator',
    modifier     varchar(100)     comment 'modifier',
    gmt_create   timestamp        default current_timestamp comment 'create time',
    gmt_update   datetime         default current_timestamp on update current_timestamp comment 'update time',
    primary key (id),
    unique key (component)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for hzb_status_page_config
-- ----------------------------
DROP TABLE IF EXISTS  hzb_status_page_config ;
CREATE TABLE  hzb_status_page_config
(
    id             bigint           not null auto_increment comment 'ID',
    org_id         bigint           not null comment 'org id',
    component      varchar(255)     not null comment 'component name',
    desc           varchar(255)     comment 'component description',
    tag            varchar(255)     not null comment 'match tag{labelName:labelValue}',
    method         tinyint          not null default 0 comment 'calculate status method: 0-auto 1-manual',
    config_state   tinyint          comment 'config state when use auto method: 0-Normal 1-Abnormal 2-Suspended',
    current_state  tinyint          comment 'component current state: 0-Normal 1-Abnormal 2-Suspended',
    creator        varchar(100)     comment 'creator',
    modifier       varchar(100)     comment 'modifier',
    gmt_create     timestamp        default current_timestamp comment 'create time',
    gmt_update     datetime         default current_timestamp on update current_timestamp comment 'update time',
    primary key (id)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for hzb_status_page_history
-- ----------------------------
DROP TABLE IF EXISTS  hzb_status_page_history ;
CREATE TABLE  hzb_status_page_history
(
    id           bigint           not null auto_increment comment 'ID',
    component_id bigint           not null comment 'component id',
    state        tinyint          not null comment 'component state: 0-Normal 1-Abnormal 2-Suspended',
    timestamp    bigint           not null comment 'state calculate timestamp',
    creator      varchar(100)     comment 'creator',
    modifier     varchar(100)     comment 'modifier',
    gmt_create   timestamp        default current_timestamp comment 'create time',
    gmt_update   datetime         default current_timestamp on update current_timestamp comment 'update time',
    primary key (id)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
```

## Checklist

- [x]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
image

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
image

**Comment by tomsun28** [comment]
https://discordstatus.com/#

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
https://discordstatus.com/#

**Comment by tomsun28** [comment]
image

**Comment by tomsun28** [comment]
14641706533983_ pic

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
14641706533983_ pic

**Comment by tomsun28** [comment]
image

image

done! please help review and merge. @zqr10159

**Comment by zqr10159** [comment]
OK.let me see

**Review by zqr10159 — APPROVED** [review]
LGTM

**Pull request merged**
