### PR TITLE
bugfix monitoring param number limit range

### PR DESCRIPTION
**Pull request by qyaaaa**
## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by qyaaaa** [comment]
Fixes #1210

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Fixes #1210

**Review by tomsun28 — APPROVED** [review]
LGTM👍👍 thanks

**Comment by tomsun28** [comment]
@all-contributors please add @qyaaaa  for code

**Pull request merged**
