### PR TITLE
[doc] correct copyright info

### PR DESCRIPTION
**Pull request by earthjasonlin**

### CODE REVIEW

**Review by earthjasonlin — COMMENTED** [review]
这个地方其实是不是可以直接用 ``&copy;`` ？

**Comment by tomsun28** [comment]
> 这个地方其实是不是可以直接用 `&copy;` ？

👍👍 可以可以 这样简单些

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Is it possible to use `©` directly in this place?

👍👍 It can be easier

**Comment by tomsun28** [comment]
@earthjasonlin 还有这个位置得辛苦改下 https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/layout/basic/basic.component.ts#L83

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@earthjasonlin and this position has to be changed https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/layout/basic/basic.component.ts#L83

**Comment by earthjasonlin** [comment]
> @earthjasonlin 还有这个位置得辛苦改下 https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/layout/basic/basic.component.ts#L83

改完了

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> @earthjasonlin and this position has to be changed https://github.com/dromara/hertzbeat/blob/master/web-app/src/app/layout/basic/basic.component.ts#L83

Finished

**Review by tomsun28 — APPROVED** [review]
👍

**Comment by tomsun28** [comment]
@all-contributors please add @earthjasonlin  for code, doc

**Pull request merged**
