### PR TITLE
refactor verify http collect response status code

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

refactor verify http collect response status code
support `api monitoring` can custom update success status code in web ui

image

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
should update h2 database with sql: 
```
ALTER TABLE HZB_PARAM  DROP CONSTRAINT CONSTRAINT_82; 
```

**Comment by tomsun28** [comment]
4xx , 5xx, 3xx, 2xx may better

**Comment by l646505418** [comment]
> 4xx , 5xx, 3xx, 2xx may better

mayeb hertzbeat is widely used by developers and devops, so they should be very familiar with shell and regex
So maybe 2**will be better?

**Comment by tomsun28** [comment]
> > 4xx , 5xx, 3xx, 2xx may better
> 
> mayeb hertzbeat is widely used by developers and devops, so they should be very familiar with shell and regex So maybe 2**will be better?

ok, we can support all. haha

**Review by l646505418 — APPROVED** [review]

**Pull request merged**
