### PR TITLE
support enable alert threshold auto resolved notice

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

support enable alert threshold auto resolved notice

image

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

**Review by Ceilzcx — APPROVED** [review]

**Comment by Ceilzcx** [comment]
恢复感觉用recover这个单词更好一点

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is better to use the word recover to recover

**Comment by tomsun28** [comment]
> 恢复感觉用recover这个单词更好一点

👍 已更新

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> It feels better to use the word recover for recovery

👍 Updated

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
